// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');
const prettier = require('eslint-plugin-prettier/recommended');

module.exports = defineConfig([
  expoConfig,
  prettier,
  {
    ignores: [
      'node_modules/**',
      '.expo/**',
      // Generated by `expo start` for typed routes; gitignored.
      'expo-env.d.ts',
      'dist/**',
      'android/**',
      'ios/**',
      'Android app design questions/**',
      // Supabase Edge Function entry points run on Deno, with URL imports.
      // Their rules live beside them in logic.ts, which is linted and tested.
      'supabase/functions/*/index.ts',
    ],
  },
]);
